<?php

use Drupal\Core\Entity\EntityInterface;

function stockblock_block_presave($entity) {
kint($entity);
}

// function mailbox_form_submit(array $form, $form_state){
//             $values = $form_state->getValue('email_id');
//             $config = \Drupal::config('mailbox.adminsettings');
//             $credentials = $config->get('mailbox_message');
//              $ch = curl_init('http://apilayer.net/api/check?access_key='.$credentials.'&email='.$values.'');
//              curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

//             // Store the data:
//             $json = curl_exec($ch);
//             curl_close($ch);

//             // // Decode JSON response:
//              $validationResult = json_decode($json, true);

//           // Access and use your preferred validation result objects
//             if ($validationResult['format_valid'] && $validationResult['smtp_check']) {
//                 drupal_set_message("valid email");

//             } else {
//                 //drupal_set_message("invalid email");
//                $form_state->setErrorByName('email_id',t('Invalid email'));
//                 //$form['#validate'][] = 'mailbox_submit_stop';
//             }
//           }


